services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_pat:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=nbp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/app

  web:
    build:
      context: angular
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules

volumes:
  postgres_pat:
